// "예측 영향 변수 TOP 5" 카드에 쓰는 피처(컬럼)명 한글 라벨. 데이터셋 컬럼은 사용자가 올리는
// CSV에 따라 달라져 전수 매핑은 불가능하므로, 자주 쓰이는(Home Credit 계열 신용평가 데이터셋)
// 컬럼만 우선 다국어 처리하고 나머지는 원래 컬럼명을 그대로 보여준다(TopFeaturesCard 참고).
export const FEATURE_LABEL: Record<string, string> = {
  SK_ID_CURR: '고객 ID',
  TARGET: '연체 여부',
  NAME_CONTRACT_TYPE: '대출 유형',
  CODE_GENDER: '성별',
  FLAG_OWN_CAR: '자동차 소유 여부',
  FLAG_OWN_REALTY: '부동산 소유 여부',
  CNT_CHILDREN: '자녀 수',
  AMT_INCOME_TOTAL: '총소득',
  AMT_CREDIT: '대출금액',
  AMT_ANNUITY: '대출 연간 상환액',
  AMT_GOODS_PRICE: '대출 대상 재화 가격',
  NAME_TYPE_SUITE: '동반인 유형',
  NAME_INCOME_TYPE: '소득 유형',
  NAME_EDUCATION_TYPE: '학력',
  NAME_FAMILY_STATUS: '결혼 상태',
  NAME_HOUSING_TYPE: '주거 형태',
  REGION_POPULATION_RELATIVE: '거주지역 인구밀도 지수',
  DAYS_BIRTH: '나이(출생 경과일)',
  DAYS_EMPLOYED: '근속일수',
  DAYS_REGISTRATION: '정보 등록 경과일수',
  DAYS_ID_PUBLISH: '신분증 발급 경과일수',
  OWN_CAR_AGE: '차량 연식',
  FLAG_MOBIL: '휴대폰 보유 여부',
  FLAG_EMP_PHONE: '직장 전화 보유 여부',
  FLAG_WORK_PHONE: '업무용 전화 보유 여부',
  FLAG_CONT_MOBILE: '연락 가능한 휴대폰 여부',
  FLAG_PHONE: '전화 보유 여부',
  FLAG_EMAIL: '이메일 보유 여부',
  OCCUPATION_TYPE: '직업군',
  CNT_FAM_MEMBERS: '가족 구성원 수',
  REGION_RATING_CLIENT: '거주지역 등급',
  REGION_RATING_CLIENT_W_CITY: '거주지역 등급(도시 반영)',
  WEEKDAY_APPR_PROCESS_START: '신청 요일',
  HOUR_APPR_PROCESS_START: '신청 시각',
  ORGANIZATION_TYPE: '근무기관 유형',
  EXT_SOURCE_1: '외부 신용평가 점수 1',
  EXT_SOURCE_2: '외부 신용평가 점수 2',
  EXT_SOURCE_3: '외부 신용평가 점수 3',
  AGE_GROUP: '연령대',
};